### ISSUE TITLE
[Features] Add possibility of classic W,A,S,D for movement

### ISSUE THREAD

**Issue by D3m0n92** [Maujoe/godot-camera-control#1]
Would it be possible to add this type of configuration for the movement?

**Comment by Maujoe** [comment]
Can you specify what you mean with "classic W,A,S,D" ?

If you want to change the keys for the movement, you can edit the Input actions from the project settings menu: Project > Project Settings > Input Map. 

By default the script use `ui_up`, `ui_down`, `ui_left`, `ui_right` for movement. So you simply can add the WASD keys to this actions or alternative you create your own actions and put the action names to the [script settings in the editor ](https://github.com/Maujoe/godot-camera-control/blob/master/assets/maujoe.camera_control/screenshots/editor_settings.png).

**Comment by drewrotunno** [comment]
This was super helpful!

**Comment by j8r** [comment]
A simple code sample adding key events to the actions will help too :slightly_smiling_face:
