### ISSUE TITLE
RQ: Exit button 

### ISSUE THREAD

**Issue by Akira1San** [Maujoe/godot-camera-control#2]
When you go to full screen, you have to do alt + F4 to quit. :)
Best would be to add a Exit button in the menu.

**Comment by Maujoe** [comment]
Hm that shouldn't be to hard but I'm not sure because the script is actually more intended for camera  specific controls and I wonder if pressing esc + pressing exit is easier/faster than just press alt + F4 (I think pressing F8 will do the job well too). or did I misunderstood something? :D

**Comment by Akira1San** [comment]
I see, then its ok.
