### ISSUE TITLE
Mouse look rotation locked when moving

### ISSUE THREAD

**Issue by j8r** [Maujoe/godot-camera-control#4]
When moving, looking around with the mouse is locked.

**Comment by j8r** [comment]
Sorry my bad, that's was my configuration - pretty annoying :sweat_smile:

**Comment by j8r** [comment]
Anyway, another topic: I think it would be good to have a simple toggle to disable warnings in development.

**Comment by Maujoe** [comment]
Yes, I agree, the most of the time the script prints unnecessary output. I will add a way to enable/disable warnings.

There also 3 variable shadowing warnings in the gui that I will fix.

**Comment by j8r** [comment]
@Maujoe I'm making a PR with "nice" default. This will remove the need of warnings.

**Comment by j8r** [comment]
@Maujoe I'm making a PR with "good" defaults. This will remove the need of warnings.

**Comment by j8r** [comment]
Never mind, I noticed Input Map has already sane defaults.
So, I agree with you - I let you do :+1:
